### PR TITLE
Samw/allow schema import over changes

### PR DESCRIPTION
**Pull request by swwilson-bsi**
Need the ability to import new schemas and to update existing schemas even if the briefcase contains local, un-pushed changes.

### CODE REVIEW

**Comment by pmconne** [comment]
```
> imodeljs-native-typescript-api@0.0.1 buildAndLint
> npm run -s build && npm run -s lint

D:\vsts_a\10\bbsrc\imodel-native\iModelJsNodeAddon\api_package\ts\src\test\importSchema.test.ts(9,26): error sort-imports : Member 'Logger' of the import declaration should be sorted alphabetically.
D:\vsts_a\10\bbsrc\imodel-native\iModelJsNodeAddon\api_package\ts\src\test\importSchema.test.ts(13,24): error sort-imports : Member 'clearRegistry' of the import declaration should be sorted alphabetically.
D:\vsts_a\10\bbsrc\imodel-native\iModelJsNodeAddon\api_package\ts\src\test\importSchema.test.ts(111,28): error @typescript-eslint/dot-notation : ["property1"] is better written in dot notation.
D:\vsts_a\10\bbsrc\imodel-native\iModelJsNodeAddon\api_package\ts\src\test\importSchema.test.ts(134,28): error @typescript-eslint/dot-notation : ["property1"] is better written in dot notation.
D:\vsts_a\10\bbsrc\imodel-native\iModelJsNodeAddon\api_package\ts\src\test\importSchema.test.ts(140,28): error @typescript-eslint/dot-notation : ["property1"] is better written in dot notation.
D:\vsts_a\10\bbsrc\imodel-native\iModelJsNodeAddon\api_package\ts\src\test\importSchema.test.ts(141,28): error @typescript-eslint/dot-notation : ["property2"] is better written in dot notation.
D:\vsts_a\10\bbsrc\imodel-native\iModelJsNodeAddon\api_package\ts\src\test\loadMetaData.ts(11,41): error @typescript-eslint/member-delimiter-style : Unexpected separator (;).
D:\vsts_a\10\bbsrc\imodel-native\iModelJsNodeAddon\api_package\ts\src\test\loadMetaData.ts(45,59): error @typescript-eslint/member-delimiter-style : Unexpected separator (;).
```

**Comment by kabentley** [comment]
This can only work after @khanaffan  finishes his change to use the "schema sync cloudsqlite db". Right?

**Comment by swwilson-bsi** [comment]
@khanaffan will my PR cause schema change merging problems?

**Comment by khanaffan** [comment]
> @khanaffan will my PR cause schema change merging problems?

no.

**Comment by kabentley** [comment]
> > @khanaffan will my PR cause schema change merging problems?
> 
> no.

Until @khanaffan's PR to synchronize schema changes finishes you must hold the schema lock on the entire iModel to make schema changes or you *will* cause merging problems. That makes this useless for LiveSync until he finishes it and we get the blob container service working.

**Comment by swwilson-bsi** [comment]
Live sync can't import schemas until the no-local-changes restriction is removed. This is blocking live sync progress - it's difficult even to hack a demo together. If the schema sync db PR is going to take a while, I would prefer to complete my PR just to get past the no-local-changes restrictions. If that requires an exclusive lock on the iModel, I could implement that as a short-term work-around in live sync.

**Comment by khanaffan** [comment]
@swwilson-bsi  i have pulled this branch into https://github.com/iTwin/imodel-native/pull/148

**Comment by swwilson-bsi** [comment]
@khanaffan one more change to fix tests: https://github.com/iTwin/imodel-native/pull/313/commits/0cdf303d26037451d5f07835cfb80815f521990d

**Comment by khanaffan** [comment]
@swwilson-bsi  you can close this PR my native PR is already merged which had your change a month back. https://github.com/iTwin/imodel-native/pull/148

**Comment by khanaffan** [comment]
@swwilson-bsi This PR has no changes. (Files changed - 0). I already pulled this branch into another PR related to schema sync.

**Pull request closed without merging**
