### PR TITLE
Fail on data conflicts instead of suppressing and pushing a potential bad changeset to hub

### PR DESCRIPTION
**Pull request by khanaffan**
itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/6373

### CODE REVIEW

**Comment by pmconne** [comment]
PR link is supposed to be `itwinjs-core: ...` not `itwinjs: ...`.

**Review by rschili — APPROVED** [review]
Approving, I was going to ask about a test, but I see you created one on the itwin side.

**Review by swwilson-bsi — APPROVED** [review]

**Pull request merged**
