### PR TITLE
implement constant lod mapping in tiles

### PR DESCRIPTION
**Pull request by MarcNeely**
itwinjs-core: https://github.com/iTwin/itwinjs-core/tree/constant-lod-mapping
imodel-native-internal: https://github.com/iTwin/imodel-native-internal/tree/constant-lod-mapping

Implements the changes needed for writing constant lod texture mapping properties to the tiles and using them for display.

### CODE REVIEW

**Review by pmconne — APPROVED** [review]

**Review by markschlosseratbentley — APPROVED** [review]

**Comment by pmconne** [comment]
@DanRod1999 help please.

**Comment by DanRod1999** [comment]
> @DanRod1999 help please. Native builds succeeded, we want to rerun the failed itwinjs-core build after having pushed fix.

I'll fix the docs to make it clearer. However, the `imodel-native PR validation` is not a pipeline which is why azp run did not work. That status check get set by your [native-internal pipeline](https://github.com/iTwin/imodel-native-internal/pull/91). Because that pipeline failed, the native PR status check failed. So to fix this you need to get the Internal pipeline to succeed

**Comment by pmconne** [comment]
@MarcNeely are you looking into test failure?
```
--[ FAILURE: @itwin/core-backend ]-----------------[ 2 minutes 34.5 seconds ]--


  381 passing (2m)
  1 failing

  1) RenderMaterialElement
       insert
         normal map with constant lod parameters:

      AssertionError: expected { HasBaseColor: false, …(8) } to deeply equal { …(9) }
      + expected - actual
  ...28 lines omitted...
           "Pattern": {
             "TextureId": "0x55"
             "pattern_angle": 1
```

**Comment by MarcNeely** [comment]
> @MarcNeely are you looking into test failure?

Yep

**Pull request merged**
