### PR TITLE
Changed nasm (used by libjpegturbo) to a upack; updated to latest version

### PR DESCRIPTION
**Pull request by chuckkir**
Libjpegturbo uses nasm from Hg. I switched it to a upack as well as updated to the latest version and switched from x86 to x64.

### CODE REVIEW

**Comment by pmconne** [comment]
Can't test for image regressions until ImageTests is updated to pull from new repos.

**Comment by chuckkir** [comment]
This is required to make the open source repo independently buildable. @DStradley please let me know if you need any help.

**Review by pmconne — APPROVED** [review]

**Comment by pmconne** [comment]
@calebmshafer is this the last of the native changes required for 3.5 release?

**Comment by calebmshafer** [comment]
@pmconne verifying now.

**Pull request merged**
