### PR TITLE
Fix computeRangesForText

### PR DESCRIPTION
**Pull request by pmconne**
Fix bone-headed mistakes in #705.

itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/6572

### CODE REVIEW

**Review by markschlosseratbentley — APPROVED** [review]

**Review by bbastings — APPROVED** [review]

**Comment by pmconne** [comment]
Android build failed twice. @aruniverse, who can decipher this?
```
2024-04-12T20:35:18.8738636Z [== Building D:\vsts_a\4\b\AndroidARM64\GeomTst\prj\app\libs\arm64-v8a\gdb.setup, (D:\vsts_a\4\b\AndroidARM64\GeomTst\prj\app\libs\arm64-v8a\libAndroidTestJni.so) ==]
2024-04-12T20:35:18.8739147Z "C:\DevTools\python312\python.exe" D:\vsts_a\4\bbsrc\bsicommon\build\CopyWithSymlinks.py D:\vsts_a\4\b\AndroidARM64\GeomTst\prj D:\vsts_a\4\b\AndroidARM64\static\BuildContexts\geomlibs\Delivery\ANJUP --excludePattern=intermediates
2024-04-12T20:35:18.8739409Z 
2024-04-12T20:35:18.8739755Z BentleyBuildMake D:\vsts_a\4\b\AndroidARM64\static\BuildContexts\geomlibs\SubParts\BeGTest\Android\BuildApk.mke -dTEST_COLLECTION_PRODUCT=GeomLibs-Tests -dTEST_SHORT_NAME=GeomTst
2024-04-12T20:35:18.8740020Z BentleyBuildMake Utility. Version 10.01.00.57, Jan 29 2024
2024-04-12T20:35:18.8740213Z Fri Apr 12 13:34:07 2024
2024-04-12T20:35:18.8740456Z Using toolset 'ANDROID_CLANG' targetting 'AndroidARM64'.
2024-04-12T20:35:18.8740727Z toolset> Using Android NDK at 'D:\vsts_a\4\b\Tools\androidndk_r25c\'.
2024-04-12T20:35:18.8741005Z toolset> Using Android SDK at 'D:\vsts_a\4\b\Tools\androidsdk_2022a\'.
2024-04-12T20:35:18.8741270Z toolset> Using Java at 'D:\vsts_a\4\b\Tools\openjdk\'.
2024-04-12T20:35:18.8741524Z toolset> Using JDK at 'D:\vsts_a\4\b\Tools\openjdk\'.
2024-04-12T20:35:18.8741767Z toolset> Using Gradle at 'D:\vsts_a\4\b\Tools\gradle\'.
2024-04-12T20:35:18.8741875Z 
2024-04-12T20:35:18.8742030Z BuildContext = D:\vsts_a\4\b\AndroidARM64\static\BuildContexts\geomlibs\
2024-04-12T20:35:18.8742148Z 
2024-04-12T20:35:18.8742338Z python D:\vsts_a\4\b\Tools\\bsiscripts\RegexReplaceInFile.py "\s+" "\n" D:\vsts_a\4\b\AndroidARM64\GeomTst\prj\gradle.properties
2024-04-12T20:35:18.8742486Z 
2024-04-12T20:35:18.8742600Z ~putenv DEBUG=
2024-04-12T20:35:18.8742808Z ~putenv GRADLE_OPTS=-Xmx8192m
2024-04-12T20:35:18.8742897Z 
2024-04-12T20:35:18.8743191Z D:\vsts_a\4\b\Tools\gradle\bin\gradle --project-dir D:\vsts_a\4\b\AndroidARM64\GeomTst\prj --no-daemon --quiet build assembleAndroidTest
2024-04-12T20:35:18.8743797Z D:/vsts_a/4/b/Tools/androidndk_r25c/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-strip.exe: error: 'D:\vsts_a\4\b\AndroidARM64\GeomTst\prj\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\gdb.setup': The file was not recognized as a valid object file
2024-04-12T20:35:18.8744022Z 
2024-04-12T20:35:18.8744465Z D:/vsts_a/4/b/Tools/androidndk_r25c/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-strip.exe: error: 'D:\vsts_a\4\b\AndroidARM64\GeomTst\prj\app\build\intermediates\merged_native_libs\release\out\lib\arm64-v8a\gdb.setup': The file was not recognized as a valid object file
2024-04-12T20:35:18.8744684Z 
2024-04-12T20:35:18.8744749Z 
2024-04-12T20:35:18.8744890Z FAILURE: Build failed with an exception.
2024-04-12T20:35:18.8744986Z 
2024-04-12T20:35:18.8745102Z * What went wrong:
2024-04-12T20:35:18.8745422Z A problem was found with the configuration of task ':app:processDebugResources' (type 'LinkApplicationAndroidResourcesTask').
2024-04-12T20:35:18.8745959Z   - In plugin 'com.android.internal.version-check' type 'com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask' property 'androidJarInput.androidJar' specifies file 'D:\vsts_a\4\b\Tools\androidsdk_2022a\platforms\android-28\android.jar' which doesn't exist.
2024-04-12T20:35:18.8746196Z 
2024-04-12T20:35:18.8746422Z     Reason: An input file was expected to be present but it doesn't exist.
2024-04-12T20:35:18.8746538Z 
2024-04-12T20:35:18.8746659Z     Possible solutions:
2024-04-12T20:35:18.8746823Z       1. Make sure the file exists before the task is called.
2024-04-12T20:35:18.8747022Z       2. Make sure that the task which produces the file is declared as an input.
2024-04-12T20:35:18.8747131Z 
2024-04-12T20:35:18.8747327Z     Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#input_file_does_not_exist for more details about this problem.
2024-04-12T20:35:18.8747486Z 
2024-04-12T20:35:18.8747598Z * Try:
2024-04-12T20:35:18.8747813Z > Run with --stacktrace option to get the stack trace.
2024-04-12T20:35:18.8748065Z > Run with --info or --debug option to get more log output.
2024-04-12T20:35:18.8748291Z > Run with --scan to get full insights.
2024-04-12T20:35:18.8748384Z 
2024-04-12T20:35:18.8748580Z * Get more help at https://help.gradle.org
2024-04-12T20:35:18.8748677Z 
2024-04-12T20:35:18.8748795Z BUILD FAILED in 26s
2024-04-12T20:35:18.8748937Z BBMake: call trace
2024-04-12T20:35:18.8749134Z     line:   42, D:\vsts_a\4\b\AndroidARM64\static\BuildContexts\geomlibs\SubParts\BeGTest\Android\BuildApk.mke
2024-04-12T20:35:18.8749385Z     line:  232, D:\vsts_a\4\b\AndroidARM64\static\BuildContexts\geomlibs\SubParts\BeGTest\Android\MakeJUnitTestProject.mke
```

**Comment by aruniverse** [comment]
> Android build failed twice. @aruniverse, who can decipher this?
> 
> ```
> 2024-04-12T20:35:18.8738636Z [== Building D:\vsts_a\4\b\AndroidARM64\GeomTst\prj\app\libs\arm64-v8a\gdb.setup, (D:\vsts_a\4\b\AndroidARM64\GeomTst\prj\app\libs\arm64-v8a\libAndroidTestJni.so) ==]
> 2024-04-12T20:35:18.8739147Z "C:\DevTools\python312\python.exe" D:\vsts_a\4\bbsrc\bsicommon\build\CopyWithSymlinks.py D:\vsts_a\4\b\AndroidARM64\GeomTst\prj D:\vsts_a\4\b\AndroidARM64\static\BuildContexts\geomlibs\Delivery\ANJUP --excludePattern=intermediates
> 2024-04-12T20:35:18.8739409Z 
> 2024-04-12T20:35:18.8739755Z BentleyBuildMake D:\vsts_a\4\b\AndroidARM64\static\BuildContexts\geomlibs\SubParts\BeGTest\Android\BuildApk.mke -dTEST_COLLECTION_PRODUCT=GeomLibs-Tests -dTEST_SHORT_NAME=GeomTst
> 2024-04-12T20:35:18.8740020Z BentleyBuildMake Utility. Version 10.01.00.57, Jan 29 2024
> 2024-04-12T20:35:18.8740213Z Fri Apr 12 13:34:07 2024
> 2024-04-12T20:35:18.8740456Z Using toolset 'ANDROID_CLANG' targetting 'AndroidARM64'.
> 2024-04-12T20:35:18.8740727Z toolset> Using Android NDK at 'D:\vsts_a\4\b\Tools\androidndk_r25c\'.
> 2024-04-12T20:35:18.8741005Z toolset> Using Android SDK at 'D:\vsts_a\4\b\Tools\androidsdk_2022a\'.
> 2024-04-12T20:35:18.8741270Z toolset> Using Java at 'D:\vsts_a\4\b\Tools\openjdk\'.
> 2024-04-12T20:35:18.8741524Z toolset> Using JDK at 'D:\vsts_a\4\b\Tools\openjdk\'.
> 2024-04-12T20:35:18.8741767Z toolset> Using Gradle at 'D:\vsts_a\4\b\Tools\gradle\'.
> 2024-04-12T20:35:18.8741875Z 
> 2024-04-12T20:35:18.8742030Z BuildContext = D:\vsts_a\4\b\AndroidARM64\static\BuildContexts\geomlibs\
> 2024-04-12T20:35:18.8742148Z 
> 2024-04-12T20:35:18.8742338Z python D:\vsts_a\4\b\Tools\\bsiscripts\RegexReplaceInFile.py "\s+" "\n" D:\vsts_a\4\b\AndroidARM64\GeomTst\prj\gradle.properties
> 2024-04-12T20:35:18.8742486Z 
> 2024-04-12T20:35:18.8742600Z ~putenv DEBUG=
> 2024-04-12T20:35:18.8742808Z ~putenv GRADLE_OPTS=-Xmx8192m
> 2024-04-12T20:35:18.8742897Z 
> 2024-04-12T20:35:18.8743191Z D:\vsts_a\4\b\Tools\gradle\bin\gradle --project-dir D:\vsts_a\4\b\AndroidARM64\GeomTst\prj --no-daemon --quiet build assembleAndroidTest
> 2024-04-12T20:35:18.8743797Z D:/vsts_a/4/b/Tools/androidndk_r25c/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-strip.exe: error: 'D:\vsts_a\4\b\AndroidARM64\GeomTst\prj\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\gdb.setup': The file was not recognized as a valid object file
> 2024-04-12T20:35:18.8744022Z 
> 2024-04-12T20:35:18.8744465Z D:/vsts_a/4/b/Tools/androidndk_r25c/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-strip.exe: error: 'D:\vsts_a\4\b\AndroidARM64\GeomTst\prj\app\build\intermediates\merged_native_libs\release\out\lib\arm64-v8a\gdb.setup': The file was not recognized as a valid object file
> 2024-04-12T20:35:18.8744684Z 
> 2024-04-12T20:35:18.8744749Z 
> 2024-04-12T20:35:18.8744890Z FAILURE: Build failed with an exception.
> 2024-04-12T20:35:18.8744986Z 
> 2024-04-12T20:35:18.8745102Z * What went wrong:
> 2024-04-12T20:35:18.8745422Z A problem was found with the configuration of task ':app:processDebugResources' (type 'LinkApplicationAndroidResourcesTask').
> 2024-04-12T20:35:18.8745959Z   - In plugin 'com.android.internal.version-check' type 'com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask' property 'androidJarInput.androidJar' specifies file 'D:\vsts_a\4\b\Tools\androidsdk_2022a\platforms\android-28\android.jar' which doesn't exist.
> 2024-04-12T20:35:18.8746196Z 
> 2024-04-12T20:35:18.8746422Z     Reason: An input file was expected to be present but it doesn't exist.
> 2024-04-12T20:35:18.8746538Z 
> 2024-04-12T20:35:18.8746659Z     Possible solutions:
> 2024-04-12T20:35:18.8746823Z       1. Make sure the file exists before the task is called.
> 2024-04-12T20:35:18.8747022Z       2. Make sure that the task which produces the file is declared as an input.
> 2024-04-12T20:35:18.8747131Z 
> 2024-04-12T20:35:18.8747327Z     Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#input_file_does_not_exist for more details about this problem.
> 2024-04-12T20:35:18.8747486Z 
> 2024-04-12T20:35:18.8747598Z * Try:
> 2024-04-12T20:35:18.8747813Z > Run with --stacktrace option to get the stack trace.
> 2024-04-12T20:35:18.8748065Z > Run with --info or --debug option to get more log output.
> 2024-04-12T20:35:18.8748291Z > Run with --scan to get full insights.
> 2024-04-12T20:35:18.8748384Z 
> 2024-04-12T20:35:18.8748580Z * Get more help at https://help.gradle.org
> 2024-04-12T20:35:18.8748677Z 
> 2024-04-12T20:35:18.8748795Z BUILD FAILED in 26s
> 2024-04-12T20:35:18.8748937Z BBMake: call trace
> 2024-04-12T20:35:18.8749134Z     line:   42, D:\vsts_a\4\b\AndroidARM64\static\BuildContexts\geomlibs\SubParts\BeGTest\Android\BuildApk.mke
> 2024-04-12T20:35:18.8749385Z     line:  232, D:\vsts_a\4\b\AndroidARM64\static\BuildContexts\geomlibs\SubParts\BeGTest\Android\MakeJUnitTestProject.mke
> ```

@tcobbs-bentley @toddsouthenbentley please look into this failure

**Comment by toddsouthenbentley** [comment]
I have no idea what that error means but I noticed that the [third Android build attempt succeeded](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=2804451&view=logs&jobId=217fbd95-5c2e-5a16-52a7-4136f1b85287&j=92a9c22a-f211-5e55-0a4e-d7795c804eac). 

It ran on BuildMinion05A whereas the failures ran on BuildMinion03A. Maybe BuildMinion03A needs to be reconfigured or rebooted? 

@chuckkir any thoughts?

**Comment by tcobbs-bentley** [comment]
Regarding the Android failures, the paths are all Windows paths, so the failures are (presumably) happening on a Windows computer. Furthermore, it _appears_ that androidsdk_2022a is missing from their tool cache. I have no idea what would cause this.

**Comment by chuckkir** [comment]
03 is a newly added box and it's certainly possible something isn't quite right. We definitely reduced the amount of old stuff we install. No more python2, etc.

c:\BBToolCache\androidsdk_2022a.2022.1.0-0 does exist on the box. However there is a lot of stuff missing when I compared it to 02. For example, platforms/android-33 doesn't exist on 03 but does on 02. That same directory also doesn't exist on my pull of androidsdk_2022a.2022.1.0-0. I would expect the upack to have everything that is needed to build but it seems like maybe stuff is being pulled after the fact by something?

**Comment by chuckkir** [comment]
Reading the error, on 03 platforms\android-28 exists but there is no android.jar in it. The problem is reproducible on my dev box after deleting %srcroot%toolcache and doing an android pull. I'm not sure why the JAR is present on 02 for example. It seems likely this problem will reappear if we purge the toolcache. So @toddsouthenbentley  and @tcobbs-bentley do you know what the disconnect is? Should the jar be there?

**Comment by tcobbs-bentley** [comment]
Looking at the error again, I think the problem may be that GeomTst was never updated to use Android SDK 31. I see now that it is using SDK 28. I have no idea where GeomTst is located. I don't have it on my computer, and never have, as far as I know. My guess is that it continued to work on existing machines because they already had SDK 28 in their tool cache when we upgraded to SDK 31.

**Comment by pmconne** [comment]
@tcobbs-bentley would you mind filing an issue and moving this discussion there?

**Comment by chuckkir** [comment]
Did you do a pull? It seems to be part of a normal pull and build on a dev box. I can’t imagine you don’t have it, although it might be a relatively recent addition.

**Comment by tcobbs-bentley** [comment]
> @tcobbs-bentley would you mind filing an issue and moving this discussion there?

Done: https://github.com/iTwin/itwinjs-backlog/issues/1090

**Comment by pmconne** [comment]
@danrod1999 @RohitPtnkr1996 Profile Version Validation is running against my linked itwinjs-core branch and imodel-native **main** for some reason?

```
Current commit: 982f304af9fc1e182537b6b712f9cf20230b1b00
itwinjs-core commit: bfddb38dee0231effda0a966209f42873848cbb2
itwinjs-core branch: pmc/textblock
imodel-native commit: NONE
imodel-native branch: main
```

```
--[ FAILURE: @itwin/core-backend ]--------------------------[ 10.58 seconds ]--

src/IModelDb.ts(1449,33): error TS2339: Property 'computeRangesForText' does not exist on type 'DgnDb'.
```

**Comment by RohitPtnkr1996** [comment]
The profile version repo wasn't updated after the 4.0.0.5 merge. I've done the update.
The builds should now pass.
@pmconne

**Pull request merged**
