### PR TITLE
Update BeGTest to compile with Android SDK 31

### PR DESCRIPTION
**Pull request by tcobbs-bentley**
This is hopefully a fix for https://github.com/iTwin/itwinjs-backlog/issues/1090

### CODE REVIEW

**Comment by tcobbs-bentley** [comment]
@chuckkir Is there any way to force it to run on the machine that was failing?

**Comment by chuckkir** [comment]
It fails on my dev box so probably easiest to get it working on your box. Delete toolcache before your pull.

bb -a androidarm64 -s imodelnative g
bb -a androidarm64 -s imodelnative b --tmrbuild --noprompt

If you really want to build on the Minion, you can force it with a tweak to the pipeline.yml to add that as a demand, and I have a branch I frequently use "chuck/buildOnSpecifcBox" in imodel-native-internal that I was using to test 03-A. To build, use the imodel-native-internal build pipeline and select that branch. Currently it's set up with all builds on windows to go to 03-A and I choose which stages I want to run when creating the pipeline build. That's the "stages to run" option or something like that.

**Comment by tcobbs-bentley** [comment]
> It fails on my dev box so probably easiest to get it working on your box. Delete toolcache before your pull.
> 
> bb -a androidarm64 -s imodelnative g bb -a androidarm64 -s imodelnative b --tmrbuild --noprompt
> 
> If you really want to build on the Minion, you can force it with a tweak to the pipeline.yml to add that as a demand, and I have a branch I frequently use "chuck/buildOnSpecifcBox" in imodel-native-internal that I was using to test 03-A. To build, use the imodel-native-internal build pipeline and select that branch. Currently it's set up with all builds on windows to go to 03-A and I choose which stages I want to run when creating the pipeline build. That's the "stages to run" option or something like that.

Unfortunately, local build on Mac doesn't check out the right packages for toolcache. I can see in the build output that it used the androidsdk_2022a upack for the SDK, and that only contains SDK 31 (as you pointed out elsewhere). I'll try your buildOnSpecificBox.

**Comment by tcobbs-bentley** [comment]
Sort of, but since I haven't done it there it's going to take a long time to do the initial bootstrap, so I had hoped to just use the other solution you suggested. Having said that, I'll go ahead and do the bootstrap on my Windows box.

**Comment by tcobbs-bentley** [comment]
I reproduced the SDK 28 failure on my Windows computer. I am now rerunning the TMR build after updating to this branch to verify that it fixes the problem.

**Comment by tcobbs-bentley** [comment]
After updating to SDK 31, the build failed with a heap error, which I corrected with PR in bsicommon.

**Comment by tcobbs-bentley** [comment]
@pmconne To the best of my ability to determine, this PR fixes the intermittent build problem you saw relating to one of the Windows CI machines being unable to build imodel-native. I tested it locally on my Windows laptop.

**Review by pmconne — APPROVED** [review]

**Pull request merged**
