### PR TITLE
Upgrade to OpenSSL 3

### PR DESCRIPTION
**Pull request by DanRod1999**
https://github.com/iTwin/imodel-native/issues/135

Successfully built on all platforms however required changes in this PR: https://github.com/iTwin/imodel-native-internal/pull/73

imodel-native-internal: https://github.com/iTwin/imodel-native-internal/tree/openssl-suppress-deprecated

### CODE REVIEW

**Comment by pmconne** [comment]
PR title should be "Upgrade to OpenSSL 3" or something similar?

**Comment by DanRod1999** [comment]
> PR title should be "Upgrade to OpenSSL 3" or something similar?

Git created the name automatically, and I was paying attention when I created the draft, thanks

**Review by pmconne — APPROVED** [review]

**Review by nick4598 — APPROVED** [review]

**Pull request merged**
