### PR TITLE
Fix crash when closing cached connection try to remove sql functions

### PR DESCRIPTION
**Pull request by khanaffan**
The crash is caused by close primary connection by the time cache connection is closed. The fix is to not attempt to remove sql functions as they already deleted when primary connection was closed.

[Sentry.io crash](https://bentley-systems-inc.sentry.io/issues/4887884042/?alert_rule_id=9206371&alert_timestamp=1705584695496&alert_type=email&notification_uuid=a6c12c4f-03cb-4b14-8ccd-363d900f10c3&project=1520306&referrer=alert_email) `EXCEPTION_ACCESS_VIOLATION_READ / 0x254d0e38928`

### CODE REVIEW

**Comment by pmconne** [comment]
@khanaffan this has been recurring frequently. I thought you fixed it long ago?
`libc++abi: terminating due to uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument`

**Review by pmconne — APPROVED** [review]

**Comment by khanaffan** [comment]
> @khanaffan this has been recurring frequently. I thought you fixed it long ago? `libc++abi: terminating due to uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument`

Yes, it was due to a global mutex in ECObjects which we fixed. I am not sure why this showed up in this PR. Let me investigate.

**Comment by pmconne** [comment]
> I am not sure why this showed up in this PR.

It has been showing up in other PRs prior to this one, too.

**Comment by khanaffan** [comment]
So I started my M1 and it seem to fail every time on core-full-stack-test on master. Its different location every time probably on IModelHost.shutdown(). I am setting up native-addon debug build to figure out what its causing it.  
```
libc++abi: terminating due to uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
```

**Comment by khanaffan** [comment]
Logged issue for the crash. https://github.com/iTwin/itwinjs-backlog/issues/1021

**Pull request merged**
