### PR TITLE
Fixed the place curve issue (through points tool) in FixedStructs.cpp

### PR DESCRIPTION
**Pull request by saeeedtorabi**
itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/6789

### CODE REVIEW

**Review by dassaf4 — APPROVED** [review]

**Review by pmconne — CHANGES_REQUESTED** [review]
Don't merge this yet if it depends on linked itwinjs-core PR.

**Comment by saeeedtorabi** [comment]
> Don't merge this yet if it depends on linked itwinjs-core PR.

Yes, I just linked the iTwin PR.

**Comment by pmconne** [comment]
Please describe in your PR title and/or description what "the issue" is.

**Review by pmconne — APPROVED** [review]

**Pull request merged**
