### PR TITLE
Fix column infos for abbreviate blobs flag

### PR DESCRIPTION
**Pull request by rschili**
itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/7323

Fixes https://github.com/iTwin/itwinjs-backlog/issues/1319

The flag was initialized to true for metadata generation and only later updated to the desired value.
Due to caching, previous value would leak into the next query's metadata generation.

### CODE REVIEW

**Review by pmconne — APPROVED** [review]

**Review by khanaffan — APPROVED** [review]

**Comment by rschili** [comment]
https://github.com/Mergifyio backport release/4.10.x

**Comment by rschili** [comment]
@Mergifyio backport release/4.11.x

**Pull request merged**
