### PR TITLE
fix RenderingAsset::Relocate

### PR DESCRIPTION
**Pull request by MichaelBelousov**
fix RenderingAsset::Relocate for use by the transformer.

sibling PR with tests: https://github.com/iTwin/itwinjs-core/pull/5059
itwinjs-core: https://github.com/iTwin/itwinjs-core/tree/fix-transformer-texture-remapping

### CODE REVIEW

**Review by pmconne — APPROVED** [review]

**Review by markschlosseratbentley — APPROVED** [review]

**Comment by pmconne** [comment]
@MichaelBelousov what's this waiting on?

**Comment by MichaelBelousov** [comment]
> @MichaelBelousov what's this waiting on?

flaky tests (link incoming). Last attempt just failed due to what looked like arcgis test changes, but this branch was out of date so just updated it.

**Comment by MichaelBelousov** [comment]
@mdastous-bentley @eringram @DanRod1999 

Both PR branches are up to date, but I am getting a new cross-platform test failure as of this morning.

```
--[ FAILURE: @itwin/map-layers-formats ]--------------------[ 18.19 seconds ]--

(node:16256) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

  67 passing (476ms)
  2 failing

  1) ArcGisFeaturePBF
       should log error when readAndRender /  readFeatureInfo is called invalid response Data:
     Error: Assert: Programmer Error
      at assert (D:\vsts_a\126\s\core\bentley\src\Assert.ts:46:9)
  ...4 lines omitted...
  2) ArcGisFeatureProvider
       fetchTile should return undefined when to format defined:
     Error: Assert: Programmer Error
      at assert (D:\vsts_a\126\s\core\bentley\src\Assert.ts:46:9)
      at ArcGisFeatureProvider.fetchTile (src\ArcGisFeature\ArcGisFeatureProvider.ts:45:32)
      at Context.<anonymous> (src\test\ArcGisFeature\ArcGisFeatureProvider.test.ts:769:46)
      at processImmediate (node:internal/timers:471:21)
```

Any ideas why PR validation might be failing this test? Couldn't reproduce locally with this branch.

**Comment by MichaelBelousov** [comment]
> @MichaelBelousov assertions only trigger if NODE_ENV=development. Do you have that set locally? We very recently started setting it for CI jobs, to catch failed assertions during tests.

good point. rerunning.

**Comment by MichaelBelousov** [comment]
@pmconne you're right, now it fails.
Pulling and running on master

**Comment by pmconne** [comment]
FYI [PR to enable assertions during tests](https://github.com/iTwin/itwinjs-core/pull/5003) included fix for at least one of your failing tests.
```
  1) ArcGisFeatureProvider
       fetchTile should return undefined when to format defined:
     Error: Assert: Programmer Error
      at assert (D:\vsts_a\4\s\core\bentley\src\Assert.ts:46:9)
      at ArcGisFeatureProvider.fetchTile (src\ArcGisFeature\ArcGisFeatureProvider.ts:45:32)
      at Context.<anonymous> (src\test\ArcGisFeature\ArcGisFeatureProvider.test.ts:769:46)
      at processImmediate (node:internal/timers:471:21)
```

**Comment by MichaelBelousov** [comment]
it also failes on imodel02 locally

**Comment by MichaelBelousov** [comment]
ok I'll just try backporting that PR to imodel02 then

**Comment by MichaelBelousov** [comment]
@khanaffan @ColinKerr 

Something seems broken on `imodel02`

```
--[ FAILURE: @itwin/core-backend ]-----------------[ 2 minutes 55.4 seconds ]--
  379 passing (3m)
  1 failing
  1) ECSqlStatement
       getRow() with navigation properties and relationships:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at /agent/_work/1/s/core/backend/src/test/ecdb/ECSqlStatement.test.ts:2298:16
      at query (src/test/ecdb/ECSqlStatement.test.ts:24:7)
      at async /agent/_work/1/s/core/backend/src/test/ecdb/ECSqlStatement.test.ts:2292:20
```

Test failure:

Row is:
```json
{
"name":"Child 1",
"parent.id":"0x1",
"parent.relClassName":"Test.ParentHasChildren",
"myParentId":"0x1",
"myParentRelClassId":"Test.ParentHasChildren"
}
```

where `myParentRelClassId` is `Test.ParentHasChildren`, obviously not an id64.

**Comment by khanaffan** [comment]
> 

@RohitPtnkr1996 This PR https://github.com/iTwin/imodel-native/pull/146 may have caused this issue.

**Comment by MichaelBelousov** [comment]
@pmconne maybe we should consider merging this since `imodel02` has this issue directly, and @RohitPtnkr1996 can investigate fixing that?

**Comment by pmconne** [comment]
@rohan-kadkol @khanaffan or @ColinKerr please fix or revert #146.

**Comment by RohitPtnkr1996** [comment]
I'm looking into the failure.
I'll have it fixed soon.

**Pull request merged**
