### PR TITLE
Update curl to 8.9.1

### PR DESCRIPTION
**Pull request by nick4598**

### CODE REVIEW

**Comment by nick4598** [comment]
@mergifyio backport release/4.8.x

**Review by pmconne — APPROVED** [review]

**Comment by nick4598** [comment]
I requeued [IOS build failure](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=3131967&view=logs&jobId=1ea363f0-5cbb-51d7-c49f-7a6807be50ba&j=1ea363f0-5cbb-51d7-c49f-7a6807be50ba&t=0c63de15-7a5f-530a-3b37-1632f35242cc), but @tcobbs-bentley do you think this error message:

```
 "CodeSign /Volumes/Builds/vsts_work_a/55/b/iOSARM64/build/iModelJsHost/framework/IModelJsNative.framework (in target 'IModelJsNative' from project 'IModelJsNative')
    cd /Volumes/Builds/vsts_work_a/55/s/imodel-native-internal/iModelJsMobile/nonport/Framework/IModelJsNative
Signing Identity:     "Apple Development: Travis Cobbs (XXXXXXXX)"
/usr/bin/codesign --force --sign XXXXXXXXXXXXXXXXXXXX --timestamp\=none --generate-entitlement-der /Volumes/Builds/vsts_work_a/55/b/iOSARM64/build/iModelJsHost/framework/IModelJsNative.framework
error: The specified item could not be found in the keychain.
```
" was transient?

**Comment by tcobbs-bentley** [comment]
@nick4598 It could be that my certificate or provisioning profile has expired. I'll investigate.

**Comment by tcobbs-bentley** [comment]
@nick4598 The certificate expired today. I uploaded a new one, but I'm not sure if the pipeline has access to read it yet.

**Pull request merged**
