### PR TITLE
ASAN error fixes in geomlibs

### PR DESCRIPTION
**Pull request by dassaf4**
Addresses several geomlibs errors caught by ASAN.

* https://github.com/iTwin/itwinjs-backlog/issues/966
* https://github.com/iTwin/itwinjs-backlog/issues/971
* And additional errors in comment details.
* Add new test to verify loosened tolerance in B-spline curve periodic closure roundtrip (backport from PPBase)

### CODE REVIEW

**Review by MichaelBelousov — APPROVED** [review]
I did not study the change, but I did checkout the branch build with ASAN, and it appears to get past that test now and instead crash on anther one. So approving this as a fix, I made a separate issue for the new crash

**Comment by dassaf4** [comment]
Converting to draft so that this PR can collect fixes for all ASAN errors detected this go-around.

**Comment by MichaelBelousov** [comment]
another one:
<details>
<pre>
[----------] 4 tests from RecursiveClipSets
[ RUN      ] RecursiveClipSets.Test1
=================================================================
==63994==ERROR: AddressSanitizer: container-overflow on address 0x61000002fca0 at pc 0x00010537e34c bp 0x00030e8f7160 sp 0x00030e8f7158
READ of size 8 at 0x61000002fca0 thread T1
    #0 0x10537e34b in BentleyM0200::DPoint3d::Scale(double) refdpoint3d.cpp:1899
    #1 0x104762ac8 in RecursiveClipSets_Test1_Test::TestBody() t_ClipPlaneSet.cpp:546
    #2 0x104aa8d32 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2664
    #3 0x104aa8a56 in testing::Test::Run() gtest.cc:2703
    #4 0x104aac492 in testing::TestInfo::Run() gtest.cc:2852
    #5 0x104aaeb11 in testing::TestSuite::Run() gtest.cc:3030
    #6 0x104aef9c6 in testing::internal::UnitTestImpl::RunAllTests() gtest.cc:5933
    #7 0x104aee51e in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2664
    #8 0x104aee2a8 in testing::UnitTest::Run() gtest.cc:5499
    #9 0x104089cf4 in void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, runAllTestsWithTimeout(unsigned long long)::$_1>>(void*) thread:299
    #10 0x7ff801b71201 in _pthread_start+0x62 (libsystem_pthread.dylib:x86_64+0x6201)
    #11 0x7ff801b6cbaa in thread_start+0xe (libsystem_pthread.dylib:x86_64+0x1baa)

0x61000002fca0 is located 96 bytes inside of 192-byte region [0x61000002fc40,0x61000002fd00)
allocated by thread T1 here:
    #0 0x111da4b4d in wrap__Znwm+0x7d (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x60b4d)
    #1 0x10409b8dd in void std::__1::vector<BentleyM0200::DPoint3d, std::__1::allocator<BentleyM0200::DPoint3d>>::__push_back_slow_path<BentleyM0200::DPoint3d>(BentleyM0200::DPoint3d&&) vector:1538
    #2 0x10476346b in void SampleGeometryCreator::StrokeUnitCircle<BentleyM0200::DPoint3d>(std::__1::vector<BentleyM0200::DPoint3d, std::__1::allocator<BentleyM0200::DPoint3d>>&, unsigned long, double) SampleGeometryCreator.h:18
    #3 0x1047629e7 in RecursiveClipSets_Test1_Test::TestBody() t_ClipPlaneSet.cpp:539
    #4 0x104aa8d32 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2664
    #5 0x104aa8a56 in testing::Test::Run() gtest.cc:2703
    #6 0x104aac492 in testing::TestInfo::Run() gtest.cc:2852
    #7 0x104aaeb11 in testing::TestSuite::Run() gtest.cc:3030
    #8 0x104aef9c6 in testing::internal::UnitTestImpl::RunAllTests() gtest.cc:5933
    #9 0x104aee51e in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2664
    #10 0x104aee2a8 in testing::UnitTest::Run() gtest.cc:5499
    #11 0x104089cf4 in void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, runAllTestsWithTimeout(unsigned long long)::$_1>>(void*) thread:299
    #12 0x7ff801b71201 in _pthread_start+0x62 (libsystem_pthread.dylib:x86_64+0x6201)
    #13 0x7ff801b6cbaa in thread_start+0xe (libsystem_pthread.dylib:x86_64+0x1baa)

Thread T1 created by T0 here:
    #0 0x111d8ee6a in wrap_pthread_create+0x5a (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x4ae6a)
    #1 0x1040851d2 in main BeGTestExe.cpp:468
    #2 0x2066f33a5  (<unknown module>)

HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_container_overflow=0.
If you suspect a false positive see also: https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow.
SUMMARY: AddressSanitizer: container-overflow refdpoint3d.cpp:1899 in BentleyM0200::DPoint3d::Scale(double)
Shadow bytes around the buggy address:
  0x61000002fa00: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x61000002fa80: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x61000002fb00: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x61000002fb80: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x61000002fc00: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
=>0x61000002fc80: 00 00 00 00[fc]fc fc fc fc fc fc fc fc fc fc fc
  0x61000002fd00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x61000002fd80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x61000002fe00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x61000002fe80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x61000002ff00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==63994==ABORTING
</pre>
</details>

**Comment by dassaf4** [comment]
> another one:

This one is similar to the first. I pushed a fix.

**Comment by MichaelBelousov** [comment]
all passes for me locally now

**Pull request merged**
