### PR TITLE
Remove trailing wihte spaces

### PR DESCRIPTION
**Pull request by saeeedtorabi**

### CODE REVIEW

**Comment by pmconne** [comment]
Do IDEs like VS Code ignore whitespace changes when blaming a file (a la `git blame -w`)?

**Comment by saeeedtorabi** [comment]
> Do IDEs like VS Code ignore whitespace changes when blaming a file (a la `git blame -w`)? GitHub doesn't.

Not sure. I used this linux command on my `Git Bash` terminal to remove trailing whitespace:
``` 
find . -type f -print0 | xargs -0 sed -i 's/[[:blank:]]\+$//'
```

**Comment by dassaf4** [comment]
> Do IDEs like VS Code ignore whitespace changes when blaming a file (a la `git blame -w`)? GitHub doesn't.

VSCode does not ignore whitespace changes out-of-the-box. Maybe there's an extension/setting? (I know this because SK normalized end-of-lines 2 years ago and is the dev who gets "blamed" for most lines in iTwin core-geometry.)

**Review by dassaf4 — APPROVED** [review]
lgtm. Github lies about last blank lines being removed! I see them there when I pulled the branch.

**Pull request merged**
