### PR TITLE
Add null pointer checks in schema format copy

### PR DESCRIPTION
**Pull request by MichaelBelousov**
the `ECObjectsTest:SchemaCopyTest.CopyStandardFormatsSchema` test fails when compiled with optimizations `-Oz` in modern versions of clang (not clang-7) that assume that dereferencing a null pointer is undefined behavior and therefore null checks after the fact can be ignored.

### CODE REVIEW

**Comment by pmconne** [comment]
Do you have the generated assembly?

**Comment by MichaelBelousov** [comment]
> Do you have the generated assembly?

Here it is from gdb

clang-13
```gas
 719│ /home/mike/work/itwinjs-cospace/repos/imodel02/out/LinuxX64/static/BuildContexts/ECObjects/PublicAPI/Formatting/FormattingApi.h:
 720│ 410         bool IsIndexValid(size_t indx) const { return indx < m_proxys.size(); }
 721│    0x0000000000b64990 <+776>:   cmp    $0x3,%rdx
 722│    0x0000000000b64994 <+780>:   mov    %r12,0x68(%rsp)
 723│
 724│ 406             if (nullptr == proxy)
 # this jump is taken down to line 771 and `proxy.m_unit` is stored to the inlined register for this return (it seems to me)
 725├──> 0x0000000000b64999 <+785>:   jb     0xb64a12 <_ZN12BentleyM02003ECN8ECSchema10CopyFormatERPNS0_8ECFormatERKS2_bPKc+906>
 726│    0x0000000000b6499b <+787>:   test   %rax,%rax
 727│    0x0000000000b6499e <+790>:   je     0xb64a12 <_ZN12BentleyM02003ECN8ECSchema10CopyFormatERPNS0_8ECFormatERKS2_bPKc+906>
 728│
 729│ 337             BEU::UnitCP GetUnit() const {return m_unit;}
 730│    0x0000000000b649a0 <+792>:   mov    0x60(%rax),%rcx
 ...
 ...
 766│ /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:
 767│ 988           { return size_type(this->_M_impl._M_finish - this->_M_impl._M_start); }
 768│    0x0000000000b64a06 <+894>:   mov    0xb0(%r15),%rax
 769│    0x0000000000b64a0d <+901>:   mov    %ebp,%r8d
 770│    0x0000000000b64a10 <+904>:   jmp    0xb64a15 <_ZN12BentleyM02003ECN8ECSchema10CopyFormatERPNS0_8ECFormatERKS2_bPKc+909>
 771│    0x0000000000b64a12 <+906>:   xor    %r13d,%r13d
 772│
 773│ /home/mike/work/itwinjs-cospace/repos/imodel02/out/LinuxX64/static/BuildContexts/ECObjects/PublicAPI/Formatting/FormattingApi.h:
 774│ 337             BEU::UnitCP GetUnit() const {return m_unit;}
 775├──> 0x0000000000b64a15 <+909>:   mov    0x90(%rax),%rcx
 776│    0x0000000000b64a1c <+916>:   xor    %ebp,%ebp
 777│    0x0000000000b64a1e <+918>:   lea    0x48(%rsp),%rdx

```

rebuilding with clang-7

**Review by ColinKerr — APPROVED** [review]

**Comment by pmconne** [comment]
> `*getTargetUnit(sourceComp->GetMajorUnit()`

`getTargetUnit` returns a pointer, but you are dereferencing it unconditionally. Dereferencing a null pointer is undefined, therefore optimizer assumes `getTargetUnit` must return non-null.
You still have the same undefined behavior with your fix, the compiler just can't see it.
Perhaps there's logic somewhere that ensures the `m_unit` is never actually null, but the constructor takes `Unit` pointer, so that doesn't inspire confidence.

**Comment by MichaelBelousov** [comment]
> > `*getTargetUnit(sourceComp->GetMajorUnit()`
> 
> `getTargetUnit` returns a pointer, but you are dereferencing it unconditionally. Dereferencing a null pointer is undefined behavior, therefore optimizer assumes `getTargetUnit` must return non-null. You still have the same undefined behavior with your fix, the compiler just can't see it. Perhaps there's logic somewhere that ensures the `m_unit` is never actually null, but the constructor takes `Unit` pointer, so that doesn't inspire confidence.

:exploding_head: thanks Paul. I see that now. I will keep that in mind for the future. The logic to make sure you don't get a `UnitProxy` with a null `m_unit` is in `CompositeValueSpec::IsIndexValid` which makes `GetProxy` return a null pointer. But when I remove the dereference, expose the `CompositeValueSpec(UnitCP, UnitCP, UnitCP, UnitCP)` constructor, and pass the pointer there, the test still fails. I think there is more horrible reference casting in that path so I will do a quick check to see if I can get it to pass that way

**Comment by MichaelBelousov** [comment]
> But when I remove the dereference, expose the `CompositeValueSpec(UnitCP, UnitCP, UnitCP, UnitCP)` constructor, and pass the pointer there, the test still fails. I think there is more horrible reference casting in that path so I will do a quick check to see if I can get the test to pass that way

nope. I just managed to compile before saving the edits to one of the files. This worked. Sorry about the delay in confirming that.

**Review by pmconne — APPROVED** [review]

**Pull request merged**
