### PR TITLE
Stop supporting iOSX64 builds

### PR DESCRIPTION
**Pull request by tcobbs-bentley**
matching imodel-native-internal pr https://github.com/iTwin/imodel-native-internal/pull/695

### CODE REVIEW

**Review by pmconne — APPROVED** [review]

**Review by aruniverse — APPROVED** [review]

**Comment by DanRod1999** [comment]
This pr is blocked by imodel-native PR validation check. That should've passed on its own from the linked pr build. Going to modify the description to unlink these prs since the internal PR has already merged

**Pull request merged**
