### PR TITLE
Include class Id in EntityMetaDataProps

### PR DESCRIPTION
**Pull request by pmconne**
itwinjs-core: https://github.com/iTwin/itwinjs-core/pull/6690

### CODE REVIEW

**Comment by pmconne** [comment]
azp run /imodel-native

**Review by aruniverse — APPROVED** [review]

**Review by bbastings — COMMENTED** [review]
Looks good, and super useful too!

**Review by bbastings — APPROVED** [review]

**Review by khanaffan — APPROVED** [review]

**Pull request merged**
