### PR TITLE
Presentation: Don't post-process when loading child nodes for evaluating artifacts

### PR DESCRIPTION
**Pull request by grigasp**
This provides ~20% performance improvement for the Filtered Models Tree case where a combination of node artifacts and same-label grouping is used.

### CODE REVIEW

**Review by saskliutas — APPROVED** [review]

**Comment by grigasp** [comment]
@mergifyio backport release/4.x

**Review by jason-crow — APPROVED** [review]

**Comment by aruniverse** [comment]
some extract-api issues: https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=2276981&view=logs&j=d19babe3-8a0c-5af8-8a0a-65506880db44&t=51380f33-853e-5b62-1a56-f5d1172151df&l=247

**Comment by DanRod1999** [comment]
github/azure is not behaving correctly right now. I've seen it a few times, but this specific issue is strange. I would try pushing an empty commit just to get the github checks to refresh

**Comment by aruniverse** [comment]
i ran:

```
git commit --allow-empty -m "Empty-Commit"
git push
```
and then the pr auto completed without even running the checks

**Pull request merged**
