### PR TITLE
Ignore non-EC changes and avoid preparing classid for table with no classid column

### PR DESCRIPTION
**Pull request by khanaffan**
There were two issues reported and fixed in this PR.
1. Api throws an exception when non-EC data changes are detected.
2. Change to table with no `ECClassId` column threw an exception.

Add unit test to cover the above two cases.

### CODE REVIEW

**Review by pmconne — APPROVED** [review]

**Comment by pmconne** [comment]
Please verify that the itwinjs-core build runs before merging - seems like it hasn't been doing so reliably.

**Comment by nick4598** [comment]
Theres an open PR to fix the issue Paul mentions(itwinjs-core builds not running):  https://github.com/iTwin/imodel-native-internal/pull/159

**Pull request merged**
