### PR TITLE
Adjust tests to avoid failure due to FP rounding

### PR DESCRIPTION
**Pull request by tcobbs-bentley**
Changes in code generation in Xcode 14.3 triggered unit test failures due to differences in floating point rounding. This adjusts the factor used to calculate the maximum error for two specific tests to avoid having them fail.

### CODE REVIEW

**Review by dassaf4 — APPROVED** [review]

**Comment by tcobbs-bentley** [comment]
@ColinKerr @c-macdonald @calebmshafer @rschili This PR must be merged before @chuckkir can upgrade Xcode on the CI Macs, and that Xcode upgrade is necessary in order to be able to do sanity check tests on mobile. The only thing it is missing is approval (I just re-merged master into this PR). If there is a problem with the PR, please let me know. Otherwise, please approve.

**Review by calebmshafer — APPROVED** [review]
Approving but do you know what caused the change in rounding?

**Comment by tcobbs-bentley** [comment]
The clang that comes with Xcode 14.3 has different code generation. I found [this](https://www.gaige.net/fp-concat-accuracy.html) article.

**Comment by calebmshafer** [comment]
@tcobbs-bentley thanks for the article link!

**Pull request merged**
