### PR TITLE
Fix exception handling problem on Apple builds

### PR DESCRIPTION
**Pull request by tcobbs-bentley**
Since Apple builds don't include runtime type information (RTTI), exception handlers meant to catch a specific type and its subclasses don't work right, so the subclasses have to be caught explicitly, along with a ... fallback.

### CODE REVIEW

**Comment by pmconne** [comment]
> Apple builds don't include runtime type information (RTTI)

Is that intrinsic to the compiler, or the way we configure the compiler? Presumably it only applies to exceptions, not all types?

**Comment by tcobbs-bentley** [comment]
> > Apple builds don't include runtime type information (RTTI)
> 
> Is that intrinsic to the compiler, or the way we configure the compiler? Presumably it only applies to exceptions, not all types?

There is an option (`-frtti`) that enables runtime type information, but unfortunately that option isn't enabled for our nuget build of Google V8, so enabling it for imodel-native results in link errors between Node and V8. I am investigating generating a V8 nuget that is compiled with the option enabled, but I'm not sure if it will work, and I have no idea how long it will take me to create.

**Comment by pmconne** [comment]
> I am investigating generating a V8 nuget that is compiled with the option enabled,

That seems like a better solution. Is this PR solving an urgent problem or can it wait until you have completed your investigation?

**Comment by tcobbs-bentley** [comment]
> > I am investigating generating a V8 nuget that is compiled with the option enabled,
> 
> That seems like a better solution. Is this PR solving an urgent problem or can it wait until you have completed your investigation?

I'm trying to get unit tests working on iOS again, and without any fix they simply crash. With this fix they run (although there are 13 tests that don't pass that I have to look at). Unit tests on iOS have been broken for a long time, but the longer they don't run, the longer we have to live with not knowing if things work, so it's hard to gauge the level of urgency.

I've personally never done any buildology for Google V8, so while I will try to get RTTI into it, I'm unsure about my chances of success.

**Comment by tcobbs-bentley** [comment]
In my opinion, doing this now and reverting it if I can get RTTI into V8 is preferred. However, I can see the argument for not approving this PR.

**Review by pmconne — APPROVED** [review]
Temp workaround until we determine whether we can enable rtti or have a good reason not to.

**Pull request merged**
