### PR TITLE
Merge ares 1.19.1 for CVE

### PR DESCRIPTION
**Pull request by chuckkir**

### CODE REVIEW

**Comment by tcobbs-bentley** [comment]
@chuckkir @nick4598 Is the fact that this isn't merged possibly causing SSL errors on Android?

**Comment by nick4598** [comment]
> @chuckkir @nick4598 Is the fact that this isn't merged possibly causing SSL errors on Android? (Android checkpoint downloads are failing with an SSL error.)

It shouldn't since ares is not compiled on android.

**Comment by chuckkir** [comment]
Also it doesn't run on the platforms it is supposed to build on so not merged is currently the preferred state until I figure out what is wrong.

**Review by pmconne — APPROVED** [review]

**Pull request merged**
