### PR TITLE
Update SQLite to 3.46.1 (latest) + fix for changegroup OOM issue

### PR DESCRIPTION
**Pull request by khanaffan**
Cherry picked fix for OOM issue when grouping changeset. This was fixed on our request.

https://github.com/iTwin/sqlite/commit/253695caf33a6cbf8c02e8af1e2f2a7e57ec04a0

### CODE REVIEW

**Review by pmconne — APPROVED** [review]

**Comment by khanaffan** [comment]
Following test failing. I am investing this
```
 1) Changeset conflict handler
       DbConflictCause.NotFound - deleted row:

      AssertionError: expected +0 to equal 1
      + expected - actual
  ...12 lines omitted...
      + expected - actual

      -0
      +1
      
      at Context.<anonymous> (src\test\standalone\MergeConflict.test.ts:334:47)

```

**Comment by khanaffan** [comment]
Turn out FKNOACTION flag did not work before this update. As fix I disabled it and will open new PR to enable it and add/update test.

**Comment by nick4598** [comment]
@khanaffan, any reason we cannot backport this to 4.9? The transformation services reported that someone is hitting an error:

`failed to concatenate indirect changes: BE_SQLITE_NOMEM`

I'm waiting on 100% confirmation that is the error message, but that is what they think it is at the moment. I assume this PR would resolve a BE_SQLITE_NOMEM issue?

**Comment by nick4598** [comment]
@mergifyio backport release/4.9.x

**Pull request merged**
