### PR TITLE
Fix logger crash on app exit

### PR DESCRIPTION
**Pull request by grigasp**
Fixes https://github.com/iTwin/imodel-native/issues/706

### CODE REVIEW

**Review by pmconne — APPROVED** [review]
extract-api is probably switching the order of things when run locally vs CI...clean, build, extract-api should fix. EDIT: uh except you don't have any TypeScript changes...

**Comment by grigasp** [comment]
> extract-api is probably switching the order of things when run locally vs CI...clean, build, extract-api should fix. EDIT: uh except you don't have any TypeScript changes...

yes, this one's interesting - I contacted @DanRod1999 regarding this

**Comment by DanRod1999** [comment]
looking at some other runs, to see if they also fail. Don't really understand what's going on, but I would assume that if this problem keeps happening master branch in itwinjs-core should also be broken, but based on its run history it seems fine. Might just have to wait for the outcome of this current run.

**Comment by grigasp** [comment]
@DanRod1999 this is still failing

**Pull request merged**
